// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cigxoesyrlytguqkcqpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZ3hvZXN5cmx5dGd1cWtjcXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODA5NDMsImV4cCI6MjA3MTM1Njk0M30.KtqyYMnIQl0tO5OIi6LCyQ0pMnx-agY4vq09Ajv6sDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});